In [1]:
import numpy as np

In [5]:
# 1차원 배열 생성

x1 = np.array([1.0, 2.0, 3.0])         # array
x2 = np.array([5.0, 10.0, 15.0]) 

print(x1, x2); print()

print(type(x1), type(x2))

[1. 2. 3.] [ 5. 10. 15.]

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
x1_l = [1.0, 2.0, 3.0]                 # list
x1_l

[1.0, 2.0, 3.0]

In [6]:
# 2차원 배열

y1 =np.array([[1.0, 2.0], [3.0, 4.0]])
y2 =np.array([[5.0, 10.0], [15.0, 20.0]])

print(y1, y2); print()

print(type(y1), type(y2))

[[1. 2.]
 [3. 4.]] [[ 5. 10.]
 [15. 20.]]

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
# numpy 원소에 접근하는 방법 : x1[0] -> 1.0

print(x1[0]); print()

print(y1[0][0])

1.0

1.0


In [9]:
a_list = [1.0, 2.0, 3.0]

a_np = np.array(a_list)              # list를 array로 바꿈
a_np

array([1., 2., 3.])

In [12]:
# numpy array 생성

arr = np.arange(15)           # range(15)를 array로 만듦
arr
arr.ndim                      # n 차원
arr.shape                     # 몇 행, 몇 열 인가?
arr.size                      # 총 몇 개로 구성되어 있는가?

print(arr.ndim, arr.shape, arr.size)

1 (15,) 15


In [13]:
arr = np.arange(20).reshape(4, 5)            # .reshape(행의 갯수, 열의 갯수) 4행 5열로 만들어라.
print(arr.ndim, arr.shape, arr.size)

2 (4, 5) 20


In [79]:
arr = np.arange(20).reshape(2, 2, 5)
print(arr.ndim, arr.shape, arr.size, arr.dtype.name, arr.dtype.itemsize)
print()

print(arr)

3 (2, 2, 5) 20 int32 4

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [16]:
arr = np.arange(-5, 5, 0.5)                 # -5부터 5까지 0.5의 차이를 두고
print(arr.ndim, arr.shape, arr.size, arr.dtype.name, arr.dtype.itemsize)

1 (20,) 20 float64 8


In [18]:
arr = np.arange(-5, 5, 0.5).reshape(4, 5)
print(arr.ndim, arr.shape, arr.size, arr.dtype.name, arr.dtype.itemsize)

arr.reshape(20)

2 (4, 5) 20 float64 8


array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [19]:
# 배열 생성 : array

arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# 빈 array 생성 : empty

arr_1 = np.empty((4, 3))          # 4 by 3 인 배열 생성 -> 알 수 없는 값이 들어옴
arr_1

array([[8.78330411e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.89146896e-307, 6.09756704e+170],
       [3.27422715e+179, 7.11195617e-038, 1.10569452e+165],
       [1.28108087e+161, 6.34899188e-066, 2.16703461e+184]])

In [25]:
# 초기값을 부여하면서 array 생성 : zeros

arr_2 = np.zeros(5)              # 1차원 배열 5인 배열의 초기값은 0
print(arr_2); print()

arr_3 = np.zeros((2, 3))         # 2차원 배열 2행 3열
print(arr_3)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# 1로 초기화 하면서 배열 생성 :

arr_4 = np.ones((3, 4))
arr_4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr_5 = np.ones((3, 4), dtype = 'i')   # dtype = 'i' : 정수로, 'f' : 실수로
arr_5

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [28]:
arr_5 = np.ones((3, 4), dtype = 'i8')   # dtype = 'i8' : 8바이트
print(arr_5.dtype, arr_5.dtype.itemsize)

int64 8


In [33]:
arr_5 = np.zeros(5, dtype = 'U4')        # dtype = U4' : 문자
print(arr_5); print()

print(arr_5.dtype, arr_5.dtype.itemsize); print()

arr_6 = np.ones_like(arr_5, dtype = 'f')     # 기존 데이터를 1로 바꿈 
print(arr_6)                                 # = np.ones_like(바꾸려는 데이터, dtype = '')
                                                 # np.zeros_like() = 0으로 바꿈

['' '' '' '' '']

<U4 16

[1. 1. 1. 1. 1.]


In [31]:
arr_5 = np.zeros(3)        
print(arr_5.dtype, arr_5.dtype.itemsize)

float64 8


In [40]:
# array 연산

x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0], [3.0, 4.0]])
y2 = np.array([[5.0, 10.0], [15.0, 20.0]])
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0], [1.0], [15.0]])

print(x1 + y1)
print(x1 - y1); print()

print(x1 * y1)
print(x1 / y1); print()

print(x2 + y2)                 #[[6.0, 12.0], [18.0, 24.0]]
print(x2 - y2); print()

print(x2 + z1); print()                 # [1.0  2.0] + [-1  -2] = [0  0]
                                        # [3.0  4.0]              [2  2]
print(x2 * z1); print()

print(x1 + z2); print()

print(x1 ** 2); print()

print(x1 >= 2)


[ 6. 12. 18.]
[ -4.  -8. -12.]

[ 5. 20. 45.]
[0.2 0.2 0.2]

[[ 6. 12.]
 [18. 24.]]
[[ -4.  -8.]
 [-12. -16.]]

[[0. 0.]
 [2. 2.]]

[[-1. -4.]
 [-3. -8.]]

[[ 6.  7.  8.]
 [ 2.  3.  4.]
 [16. 17. 18.]]

[1. 4. 9.]

[False  True  True]


In [36]:
# 배열의 형 변환

print(x2.flatten()); print()          # 평탕화 시킴 : 모든 차수의 배열을 1차원으로

print(x2.reshape(2, 2))

[1. 2. 3. 4.]

[[1. 2.]
 [3. 4.]]


In [42]:
# array의 인덱싱, 슬라이싱, 반복

a = np.arange(10) ** 2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [43]:
print(print(a[3 : 5]), print(a[2]))         # [9, 16], 4
print()

print(a[ : : -1])                      # start : end : -1(step)  -> 뒤에서부터 출력

a[0:6:2] = -a[0:6:2]                   # start : end : step

[ 9 16]
4
None None

[81 64 49 36 25 16  9  4  1  0]


In [44]:
print(a)

[  0   1  -4   9 -16  25  36  49  64  81]


In [45]:
# 반복문

for x in a:
    print(x + 1, end = ' ')

1 2 -3 10 -15 26 37 50 65 82 

In [47]:
a = np.arange(1, 21, 1).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
print(a[1, 1]); print()           # 1행 1열 (0행부터 시작)

print(a[ : 2, : ]);print()

print(a[1, ]); print()

print(a[ : , -1])                 # -1은 마지막 행 또는 열을 의미(여기서는 마지막 열)

7

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 6  7  8  9 10]

[ 5 10 15 20]


In [53]:
# numpy 의 일반함수

a = np.arange(0, 6, 1)     # array[0, 1, 2, 3, 4, 5]

print(a); print()

print(np.sin(a), np.cos(a))

[0 1 2 3 4 5]

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [54]:
a = np.arange(0.01, 1, 0.05)
print(np.log(a))

[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]


In [62]:
a1 = np.array([10, 3, 4])
a2 = np.array([4, 5, 6])

print(np.maximum(a1, a2)); print()        # 큰 숫자만 나옴

print(np.minimum(a1, a2)); print()        # 작은 숫자만 나옴

print(np.sum(a1), np.sum(a2))

[10  5  6]

[4 3 4]

17 15


In [63]:
print(np.random.choice(100, 5))    # 0에서 100 사이의 숫자 중에서 5개 숫자를 선택
print()

print(np.random.rand(2, 3))        # -1에서 1까지 숫자 중에서 정규화

[94 25 43 15 92]

[[0.15826774 0.89867906 0.19084773]
 [0.82202138 0.64198306 0.06255133]]


In [67]:
a = np.array([6, 1, 3, 2, 4, 5])

print(np.argmax(a)); print()            # 제일 큰 값의 위치(인덱스) 반환

print(a[np.argmax(a)]); print()

print(np.argmin(a))                     # 제일 작은 값의 위치(인덱스) 반환

0

6

1


In [71]:
a = np.array([[0.1, 0.8, 0.2], [0.3, 0.2, 0.5], [0.9, 0.5, 0.3]])

print(np.argmax(a)); print()            # 열 무시, 그냥 제일 큰 값의 위치(인덱스) 반환

print(np.argmax(a, axis = 1)); print()           # 0축이 세로, 1축이 가로

print(np.argmax(a, axis = 0))                                            # 다시보기

6

[1 2 0]

[2 0 1]


In [74]:
np.random.seed(0)                          # seed()를 쓰면 정해진 시드의 값을 가져온다(바뀌지 않음)

print(np.random.choice(100, 5))    # 0에서 100 사이의 숫자 중에서 5개 숫자를 선택
print()

print(np.random.rand(2, 3))        # -1에서 1까지 숫자 중에서 정규화

[44 47 64 67 67]

[[0.84725174 0.6235637  0.38438171]
 [0.29753461 0.05671298 0.27265629]]


In [76]:
arr = np.arange(1, 21, 1)

print(arr[arr % 3 == 0]); print()

print(arr[arr % 4 == 1]); print()

print(arr[(arr % 3 == 0) & (arr % 4 == 1)])

[ 3  6  9 12 15 18]

[ 1  5  9 13 17]

[9]


In [78]:
print(arr % 3 == 0)     # arr[arr % 3 == 0] 이런 식으로 출력하지 않으면 True나 False의 형태로 나온다

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False]
