# numpy의 ndarray - 다차원 행렬 구조

클래스 numpy. ndarray ( shape , dtype = float , buffer = None , offset = 0 , strides = None , order = None )

배열 개체는 고정 크기 항목의 다차원 동종 배열을 나타냅니다. 

연관된 데이터 유형 객체는 배열에 있는 각 요소의 형식 -
    바이트 순서, 메모리에서 차지하는 바이트 수, 정수인지 부동 소수점 숫자인지 등을 설명합니다.

In [33]:
import numpy as np

In [42]:

a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([0.12 , 0.34, 0.45, 0.66])
c = np.array(['a' , 'b' , 'c'])
d = np.array([True, False, False, True, False, True, True])

print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Parameters(매개변수)
    
    #shape : 생성된 배열의 모양, int의 튜플
    #dtype : 데이터 유형, numpy 데이터 유형으로 해석될 수 있는 모든 개체 / 선택사항
    #buffer : 인터페이스를 노출하는 버퍼 객체, 배열을 데이터로 채우는 데 사용 / 선택사항
    #offset : 버퍼에 있는 배열 데이터의 오프셋 / 선택사항
    #strides : int 튜플, 메모리의 데이터 스트라이드 / 선택사항
    #order : {'C', 'F'}, 행 우선(C) 또는 열 우선(F) / 선택사항


In [29]:
print(np.ndarray(shape=(2,2), dtype=float, order='F'))

print()

print(np.ndarray((2,), buffer=np.array([1,2,3]),
           offset=np.int_(),
           dtype=int)) 

[[0.12 0.45]
 [0.34 0.66]]

[1 2]


In [58]:
#np.ndarray.T - 전치된 배열입니다.
print(a.T)

#np.ndarray.data - 배열 데이터의 시작을 가리키는 Python 버퍼 객체.
print(c.data)

#np.ndarray.dtype - 배열 요소의 데이터 유형입니다.
print(b.dtype)

#np.ndarray.flags - 어레이의 메모리 레이아웃에 대한 정보입니다.
print(d.flags)

#np.ndarray.flat - 배열에 대한 1차원 반복기입니다.
print(a.flat)

#np.ndarray.imag - 배열의 허수 부분입니다.
print(b.imag)

#np.ndarray.real - 배열의 실제 부분입니다.
print(d.real)

#np.ndarray.size - 배열의 요소 수입니다.
print(a.size)

#np.ndarray.itemsize - 한 배열 요소의 길이(바이트)입니다.
print(c.itemsize)

#np.ndarray.nbytes - 배열의 요소에서 사용한 총 바이트입니다.
print(d.nbytes)

#np.ndarray.ndim - 배열 차원의 수입니다.
print(b.ndim)

#np.ndarray.shape - 배열 차원의 튜플.
print(a.shape)

#np.ndarray.strides - 배열을 순회할 때 각 차원에서 단계별로 수행할 바이트 튜플입니다.
print(c.strides)

#np.ndarray.ctypes - ctypes 모듈과 배열의 상호 작용을 단순화하는 개체입니다.
print(a.ctypes)

#np.ndarray.base - 메모리가 다른 개체에서 가져온 경우 기본 개체입니다
print(d.base)

[0 1 2 3 4 5 6 7 8 9]
float64
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[0. 0. 0. 0.]
[ True False False  True False  True  True]
10
4
7
1
(10,)
(4,)
None


In [30]:
#ndarray의 ndim과 shape 메소드 : 
    #머신러닝의 텐서 구조와 차원을 알아내는 것과 동일
    
print(a.ndim, b.ndim, c.ndim)
print(a.shape, b.shape, c.shape)

1 1 1
(10,) (4,) (3,)
